excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://andreeds.github.io
title: CS807 Notebook
tagline: Resource Constrained Computing
description: Notebook for CS 807 Interactive Hardware and Embedded Computing 
paginate: 5
