excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://andreeds.github.io
title: CS807 Notebook
tagline: Resource Constrained Computing
description: André E. dos Santos <br> 200334126
paginate: 5
